### PR TITLE
Added Download Image Component

### PR DESCRIPTION
**Pull request by veerprakash28**
**What does this PR do?**
Fixed the issue of low quality images getting download. Downloads high quality image

**Changes**
- Changed the small quality download link to full
- Added icon for download instead of text
- Made separated component for the images card
- Added downloaded image link so that downlaoded image name will look like this: Image-searcher-(random8digitNumber)

### CODE REVIEW

**Comment by Vijaykv5** [comment]
There's been some conflicts in this PR @veerprakash28

**Comment by Vijaykv5** [comment]
Have you done a git pull? before commiting

**Comment by veerprakash28** [comment]
Yes, It's showing Already up to date.

**Comment by Vijaykv5** [comment]
@veerprakash28 May you can change the color of download button to **Violet**

**Comment by veerprakash28** [comment]
Sure, should I raise another PR for that?

**Comment by Vijaykv5** [comment]
I'll revert this PR and you just need to do a commit again

**Comment by veerprakash28** [comment]
ok

**Comment by Vijaykv5** [comment]
I think you need to add a PR again. May you first try with just committing

**Pull request merged**
