### PR TITLE
Uiux/addingicons

### PR DESCRIPTION
**Pull request by ayushichoudhary-19**
**Related Issue(s)**
This PR resolved the issue #41 

**Changes**
I have changed the '^' on the BottomtoTop button to FontAwesome's Chevron up solid icon.
Also, added a 'search' icon near the search bar.

**Screenshots or GIFs (if applicable)**
image
image

**Checklist**
- I have read and followed the [contributing guidelines](../CONTRIBUTING.md).
- My code follows the project's coding style and conventions.
- I have added unit tests (if applicable) to ensure the code works as expected.

**By submitting this PR, I confirm that:**
- I have reviewed my code and believe it is ready for merging.
- I understand that this PR may be subject to review and changes.
- I agree to abide by the code of conduct and contributing guidelines of this project.

### CODE REVIEW

**Comment by Vijaykv5** [comment]
is search button really neccessory. I feels like it not good. I though of a search button on right of search bar.
Also please remove the dotted border in bottontotop button

**Comment by ayushichoudhary-19** [comment]
Removed the search icon altogether.

Removed the dotted border.
image

**Comment by ayushichoudhary-19** [comment]
@Vijaykv5 please review the PR and share your feedback.

**Comment by Vijaykv5** [comment]
Thanks for contributing 🚀

**Pull request merged**
