### PR TITLE
Migrate to NextJS

### PR DESCRIPTION
**Pull request by mezotv**
**What does this PR do?**
This PR migrates the code from React to NextJS for a much better performance experience.

**Related Issue(s)**
#39 

**Changes**
- Migrate code to Next.js
- Clean up structure
- Improve SEO slightly

**Screenshots or GIFs (if applicable)**
None

**Checklist**
- [x] I have read and followed the [contributing guidelines](../CONTRIBUTING.md).
- [x] My code follows the project's coding style and conventions.
- [x] I have added unit tests (if applicable) to ensure the code works as expected.
- [x] I have updated the project documentation (if necessary).

**Additional Comments**
None

**By submitting this PR, I confirm that:**
- [x] I have reviewed my code and believe it is ready for merging.
- [x] I understand that this PR may be subject to review and changes.
- [x] I agree to abide by the code of conduct and contributing guidelines of this project.

### CODE REVIEW

**Comment by mezotv** [comment]
Netlify will need to be adjusted for this to work but that is out of my control!

**Comment by Vijaykv5** [comment]
@mezotv Thanks for your contribution but first of all you should raise the Issue inorder to work on it.
Also you must work only on the Assigned Issues

**Comment by mezotv** [comment]
> @mezotv Thanks for your contribution but first of all you should raise the Issue inorder to work on it. Also you must work only on the Assigned Issues

Want me to create an issue for this now?

**Comment by Vijaykv5** [comment]
> > @mezotv Thanks for your contribution but first of all you should raise the Issue inorder to work on it. Also you must work only on the Assigned Issues
> 
> Want me to create an issue for this now?

It must have been done before raising this PR
Actually Right now I'm not interested to Migrate to NextJS as we right now have many features to enhance and add on

**Comment by mezotv** [comment]
> It must have been done before raising this PR Actually Right now I'm not interested to Migrate to NextJS as we right now have many features to enhance and add on

I just created an issue it should be easy to add your new features to next as the code is identical!

**Comment by Vijaykv5** [comment]
@mezotv I appreciate your efforts in making this changes and adding your contributions but please by now take care to work only on the assigned issues to you
since hacktoberfest is approaching I'm making this repo for newbie as well as for other folks and many of them will be uncomfortable with Next. So I'm right now keeping it with ReactJS itself.

**Comment by mezotv** [comment]
> @mezotv I appreciate your efforts in making this changes and adding your contributions but please by now take care to work only on the assigned issues to you since hacktoberfest is approaching I'm making this repo for newbie as well as for other folks and many of them will be uncomfortable with Next. So I'm right now keeping it with ReactJS itself.

Hmm yea I don't understand your decision but good luck!

**Comment by mezotv** [comment]
Deleting this as the owner doesn't want Nextjs!

**Comment by Vijaykv5** [comment]
@mezotv You may check out other issues If you want to contribute on or may be moving onto typescript
anyway Thanks and Good luck :)

**Comment by mezotv** [comment]
> @mezotv You may check out other issues If you want to contribute on or may be moving onto typescript anyway Thanks and Good luck :)

I don't think so I spent way to much time on this anyways.

**Comment by Vijaykv5** [comment]
Ok good luck

> > @mezotv You may check out other issues If you want to contribute on or may be moving onto typescript anyway Thanks and Good luck :)
> 
> I don't think so I spent way to much time on this anyways.

**Pull request closed without merging**
